name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-docs
          
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true
          
      - name: Build documentation
        run: |
          cargo doc --workspace --all-features --no-deps --document-private-items
          cp doc/index.html target/doc/index.html
          
      - name: Deploy to main/docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          destination_dir: docs
